package d1.domain;

import d1.domain.DCL_IO_DECL_TASK;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;
@Component
@Mapper
public interface DCL_IO_DECL_TASKMapper {
    @Insert({
        "insert into DCL_IO_DECL_TASK (DECL_NO, TRADE_MODE_CODE, ",
        "CONTRACT_NO, MARK_NO, ",
        "TRADE_COUNTRY_CODE, DESP_CTRY_CODE, ",
        "TRANS_MODE_CODE, CONVYNCE_NAME, ",
        "TRANS_MEAN_NO, DESP_PORT_CODE, ",
        "PORT_STOP_CODE, ENTY_PORT_CODE, ",
        "GDS_ARVL_DATE, CMPL_DSCHRG_DT, ",
        "GOODS_PLACE, DEST_CODE, ",
        "COUNTER_CLAIM, BILL_LAD_NO, ",
        "DELIVERY_ORDER, INSP_ORG_CODE, ",
        "EXC_INSP_DEPT_CODE, DECL_CUSTM, ",
        "SPEC_DECL_FLAG, PURP_ORG_CODE, ",
        "CORRELATION_DECL_NO, CORRELATION_REASON_FLAG, ",
        "SPECL_INSP_QURA_RE, APP_CERT_CODE, ",
        "APPL_ORI, APPL_COPY_QUAN, ",
        "CUSTM_REG_NO, DECL_PERSN_CERT_NO, ",
        "DECL_PERSON_NAME, DECL_REG_NAME, ",
        "CONTACTPERSON, CONT_TEL, ",
        "CONSIGNEE_CODE, CONSIGNEE_CNAME, ",
        "CONSIGNEE_ENAME, CONSIGNOR_CNAME, ",
        "CONSIGNOR_ADDR, DECL_CODE, ",
        "DECL_DATE, DECL_GET_NO, ",
        "SPEC_PASS_FLAG, DESP_DATE, ",
        "ARRIV_PORT_CODE, CONSIGNEE_ADDR, ",
        "CONSIGNOR_CODE, ATTA_COLLECT_NAME, ",
        "IS_LIST_GOOD, IS_CONT, FFJ_FLAG, ",
        "FFJ_STATUS, RESEND_NUM, ",
        "IS_DRAW, TOTAL_VAL_US, ",
        "TOTAL_VAL_CN, CONT_CANCEL_FLAG, ",
        "FEE_HANDLE_STATE, RELS_STATE, ",
        "FLG_PORT_INLAND, ENABLE_TRANS_FLAG, ",
        "FALG_ARCHIVE, SITUATION_CODE, ",
        "SITUATION_LEVEL, PROCESS_STATUS, ",
        "OPER_CODE, OPER_TIME, ",
        "APP_CERT_NAME, DECL_REG_NO, ",
        "ENT_DECL_NO, PROCESS_LINK, ",
        "ORG_CODE, CERT_CANCEL_FLAG, ",
        "CONSIGNOR_ENAME, ARCHIVE_TIME, ",
        "TRANS_FLAG, SPLIT_BILL_LAD_NO, ",
        "ENT_UUID, DECL_TYPE, ",
        "ORG_CODE_PATH, DECL_STATUS, ",
        "IS_FEE, DECL_WORK_NO, ",
        "PURP_DEPT_CODE, DCL_IO_DECL_ID, ",
        "VSA_ORG_CODE, PORT_ORG_CODE, ",
        "PORT_DEPT_CODE, INTE_FLAG, ",
        "BRI_FLAG, CHECK_OK_FLAG, ",
        "DIS_CHARGE_FLAG, ORIG_BOX_FLAG, ",
        "VSA_ORG_CODE_PATH, INSP_ORG_CODE_PATH, ",
        "PURP_ORG_CODE_PATH, PORT_ORG_CODE_PATH, ",
        "PRI_KEY, TRANS_TYPE_TJ, ",
        "OPER_TIME_TJ, ENT_DATE, ",
        "IsCheck)",
        "values (#{declNo,jdbcType=VARCHAR}, #{tradeModeCode,jdbcType=VARCHAR}, ",
        "#{contractNo,jdbcType=VARCHAR}, #{markNo,jdbcType=VARCHAR}, ",
        "#{tradeCountryCode,jdbcType=VARCHAR}, #{despCtryCode,jdbcType=VARCHAR}, ",
        "#{transModeCode,jdbcType=VARCHAR}, #{convynceName,jdbcType=VARCHAR}, ",
        "#{transMeanNo,jdbcType=VARCHAR}, #{despPortCode,jdbcType=VARCHAR}, ",
        "#{portStopCode,jdbcType=VARCHAR}, #{entyPortCode,jdbcType=VARCHAR}, ",
        "#{gdsArvlDate,jdbcType=TIMESTAMP}, #{cmplDschrgDt,jdbcType=TIMESTAMP}, ",
        "#{goodsPlace,jdbcType=VARCHAR}, #{destCode,jdbcType=VARCHAR}, ",
        "#{counterClaim,jdbcType=TIMESTAMP}, #{billLadNo,jdbcType=VARCHAR}, ",
        "#{deliveryOrder,jdbcType=VARCHAR}, #{inspOrgCode,jdbcType=VARCHAR}, ",
        "#{excInspDeptCode,jdbcType=VARCHAR}, #{declCustm,jdbcType=VARCHAR}, ",
        "#{specDeclFlag,jdbcType=VARCHAR}, #{purpOrgCode,jdbcType=VARCHAR}, ",
        "#{correlationDeclNo,jdbcType=VARCHAR}, #{correlationReasonFlag,jdbcType=VARCHAR}, ",
        "#{speclInspQuraRe,jdbcType=VARCHAR}, #{appCertCode,jdbcType=VARCHAR}, ",
        "#{applOri,jdbcType=VARCHAR}, #{applCopyQuan,jdbcType=VARCHAR}, ",
        "#{custmRegNo,jdbcType=VARCHAR}, #{declPersnCertNo,jdbcType=VARCHAR}, ",
        "#{declPersonName,jdbcType=VARCHAR}, #{declRegName,jdbcType=VARCHAR}, ",
        "#{contactperson,jdbcType=VARCHAR}, #{contTel,jdbcType=VARCHAR}, ",
        "#{consigneeCode,jdbcType=VARCHAR}, #{consigneeCname,jdbcType=VARCHAR}, ",
        "#{consigneeEname,jdbcType=VARCHAR}, #{consignorCname,jdbcType=VARCHAR}, ",
        "#{consignorAddr,jdbcType=VARCHAR}, #{declCode,jdbcType=VARCHAR}, ",
        "#{declDate,jdbcType=TIMESTAMP}, #{declGetNo,jdbcType=VARCHAR}, ",
        "#{specPassFlag,jdbcType=VARCHAR}, #{despDate,jdbcType=TIMESTAMP}, ",
        "#{arrivPortCode,jdbcType=VARCHAR}, #{consigneeAddr,jdbcType=VARCHAR}, ",
        "#{consignorCode,jdbcType=VARCHAR}, #{attaCollectName,jdbcType=VARCHAR}, ",
        "#{isListGood,jdbcType=CHAR}, #{isCont,jdbcType=CHAR}, #{ffjFlag,jdbcType=CHAR}, ",
        "#{ffjStatus,jdbcType=CHAR}, #{resendNum,jdbcType=CHAR}, ",
        "#{isDraw,jdbcType=CHAR}, #{totalValUs,jdbcType=DECIMAL}, ",
        "#{totalValCn,jdbcType=DECIMAL}, #{contCancelFlag,jdbcType=CHAR}, ",
        "#{feeHandleState,jdbcType=VARCHAR}, #{relsState,jdbcType=VARCHAR}, ",
        "#{flgPortInland,jdbcType=CHAR}, #{enableTransFlag,jdbcType=CHAR}, ",
        "#{falgArchive,jdbcType=CHAR}, #{situationCode,jdbcType=VARCHAR}, ",
        "#{situationLevel,jdbcType=CHAR}, #{processStatus,jdbcType=VARCHAR}, ",
        "#{operCode,jdbcType=VARCHAR}, #{operTime,jdbcType=TIMESTAMP}, ",
        "#{appCertName,jdbcType=VARCHAR}, #{declRegNo,jdbcType=VARCHAR}, ",
        "#{entDeclNo,jdbcType=VARCHAR}, #{processLink,jdbcType=VARCHAR}, ",
        "#{orgCode,jdbcType=VARCHAR}, #{certCancelFlag,jdbcType=CHAR}, ",
        "#{consignorEname,jdbcType=VARCHAR}, #{archiveTime,jdbcType=TIMESTAMP}, ",
        "#{transFlag,jdbcType=VARCHAR}, #{splitBillLadNo,jdbcType=VARCHAR}, ",
        "#{entUuid,jdbcType=VARCHAR}, #{declType,jdbcType=CHAR}, ",
        "#{orgCodePath,jdbcType=VARCHAR}, #{declStatus,jdbcType=CHAR}, ",
        "#{isFee,jdbcType=CHAR}, #{declWorkNo,jdbcType=VARCHAR}, ",
        "#{purpDeptCode,jdbcType=VARCHAR}, #{dclIoDeclId,jdbcType=VARCHAR}, ",
        "#{vsaOrgCode,jdbcType=VARCHAR}, #{portOrgCode,jdbcType=VARCHAR}, ",
        "#{portDeptCode,jdbcType=VARCHAR}, #{inteFlag,jdbcType=CHAR}, ",
        "#{briFlag,jdbcType=CHAR}, #{checkOkFlag,jdbcType=CHAR}, ",
        "#{disChargeFlag,jdbcType=CHAR}, #{origBoxFlag,jdbcType=CHAR}, ",
        "#{vsaOrgCodePath,jdbcType=VARCHAR}, #{inspOrgCodePath,jdbcType=VARCHAR}, ",
        "#{purpOrgCodePath,jdbcType=VARCHAR}, #{portOrgCodePath,jdbcType=VARCHAR}, ",
        "#{priKey,jdbcType=VARCHAR}, #{transTypeTj,jdbcType=VARCHAR}, ",
        "#{operTimeTj,jdbcType=TIMESTAMP}, #{entDate,jdbcType=TIMESTAMP}, ",
        "#{ischeck,jdbcType=DECIMAL})"
    })
    int insert(DCL_IO_DECL_TASK record);

    @InsertProvider(type=DCL_IO_DECL_TASKSqlProvider.class, method="insertSelective")
    int insertSelective(DCL_IO_DECL_TASK record);

    @Select("SELECT * FROM DCL_IO_DECL WHERE \"OPER_TIME_TJ\">=to_date(#{QueryTime,jdbcType=VARCHAR}, 'yyyy-mm-dd') AND \"OPER_TIME_TJ\"<to_date(#{QueryEndTime,jdbcType=VARCHAR}, 'yyyy-mm-dd')")
    @Results({
            @Result(column="PRI_KEY", property="priKey", jdbcType= JdbcType.VARCHAR),
            @Result(column="DECL_NO", property="declNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="TRADE_MODE_CODE", property="tradeModeCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONTRACT_NO", property="contractNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="MARK_NO", property="markNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="TRADE_COUNTRY_CODE", property="tradeCountryCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="DESP_CTRY_CODE", property="despCtryCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="TRANS_MODE_CODE", property="transModeCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONVYNCE_NAME", property="convynceName", jdbcType=JdbcType.VARCHAR),
            @Result(column="TRANS_MEAN_NO", property="transMeanNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="DESP_PORT_CODE", property="despPortCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="PORT_STOP_CODE", property="portStopCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="ENTY_PORT_CODE", property="entyPortCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="GDS_ARVL_DATE", property="gdsArvlDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="CMPL_DSCHRG_DT", property="cmplDschrgDt", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="GOODS_PLACE", property="goodsPlace", jdbcType=JdbcType.VARCHAR),
            @Result(column="DEST_CODE", property="destCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="COUNTER_CLAIM", property="counterClaim", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="BILL_LAD_NO", property="billLadNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="DELIVERY_ORDER", property="deliveryOrder", jdbcType=JdbcType.VARCHAR),
            @Result(column="INSP_ORG_CODE", property="inspOrgCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="EXC_INSP_DEPT_CODE", property="excInspDeptCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="DECL_CUSTM", property="declCustm", jdbcType=JdbcType.VARCHAR),
            @Result(column="SPEC_DECL_FLAG", property="specDeclFlag", jdbcType=JdbcType.VARCHAR),
            @Result(column="PURP_ORG_CODE", property="purpOrgCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="CORRELATION_DECL_NO", property="correlationDeclNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="CORRELATION_REASON_FLAG", property="correlationReasonFlag", jdbcType=JdbcType.VARCHAR),
            @Result(column="SPECL_INSP_QURA_RE", property="speclInspQuraRe", jdbcType=JdbcType.VARCHAR),
            @Result(column="APP_CERT_CODE", property="appCertCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="APPL_ORI", property="applOri", jdbcType=JdbcType.VARCHAR),
            @Result(column="APPL_COPY_QUAN", property="applCopyQuan", jdbcType=JdbcType.VARCHAR),
            @Result(column="CUSTM_REG_NO", property="custmRegNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="DECL_PERSN_CERT_NO", property="declPersnCertNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="DECL_PERSON_NAME", property="declPersonName", jdbcType=JdbcType.VARCHAR),
            @Result(column="DECL_REG_NAME", property="declRegName", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONTACTPERSON", property="contactperson", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONT_TEL", property="contTel", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_CODE", property="consigneeCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_CNAME", property="consigneeCname", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_ENAME", property="consigneeEname", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNOR_CNAME", property="consignorCname", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNOR_ADDR", property="consignorAddr", jdbcType=JdbcType.VARCHAR),
            @Result(column="DECL_CODE", property="declCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="DECL_DATE", property="declDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="DECL_GET_NO", property="declGetNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="SPEC_PASS_FLAG", property="specPassFlag", jdbcType=JdbcType.VARCHAR),
            @Result(column="DESP_DATE", property="despDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="ARRIV_PORT_CODE", property="arrivPortCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_ADDR", property="consigneeAddr", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNOR_CODE", property="consignorCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="ATTA_COLLECT_NAME", property="attaCollectName", jdbcType=JdbcType.VARCHAR),
            @Result(column="IS_LIST_GOOD", property="isListGood", jdbcType=JdbcType.CHAR),
            @Result(column="IS_CONT", property="isCont", jdbcType=JdbcType.CHAR),
            @Result(column="FFJ_FLAG", property="ffjFlag", jdbcType=JdbcType.CHAR),
            @Result(column="FFJ_STATUS", property="ffjStatus", jdbcType=JdbcType.CHAR),
            @Result(column="RESEND_NUM", property="resendNum", jdbcType=JdbcType.CHAR),
            @Result(column="IS_DRAW", property="isDraw", jdbcType=JdbcType.CHAR),
            @Result(column="TOTAL_VAL_US", property="totalValUs", jdbcType=JdbcType.DECIMAL),
            @Result(column="TOTAL_VAL_CN", property="totalValCn", jdbcType=JdbcType.DECIMAL),
            @Result(column="CONT_CANCEL_FLAG", property="contCancelFlag", jdbcType=JdbcType.CHAR),
            @Result(column="FEE_HANDLE_STATE", property="feeHandleState", jdbcType=JdbcType.VARCHAR),
            @Result(column="RELS_STATE", property="relsState", jdbcType=JdbcType.VARCHAR),
            @Result(column="FLG_PORT_INLAND", property="flgPortInland", jdbcType=JdbcType.CHAR),
            @Result(column="ENABLE_TRANS_FLAG", property="enableTransFlag", jdbcType=JdbcType.CHAR),
            @Result(column="FALG_ARCHIVE", property="falgArchive", jdbcType=JdbcType.CHAR),
            @Result(column="SITUATION_CODE", property="situationCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="SITUATION_LEVEL", property="situationLevel", jdbcType=JdbcType.CHAR),
            @Result(column="PROCESS_STATUS", property="processStatus", jdbcType=JdbcType.VARCHAR),
            @Result(column="OPER_CODE", property="operCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="OPER_TIME", property="operTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="APP_CERT_NAME", property="appCertName", jdbcType=JdbcType.VARCHAR),
            @Result(column="DECL_REG_NO", property="declRegNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="ENT_DECL_NO", property="entDeclNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="PROCESS_LINK", property="processLink", jdbcType=JdbcType.VARCHAR),
            @Result(column="ORG_CODE", property="orgCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="CERT_CANCEL_FLAG", property="certCancelFlag", jdbcType=JdbcType.CHAR),
            @Result(column="CONSIGNOR_ENAME", property="consignorEname", jdbcType=JdbcType.VARCHAR),
            @Result(column="ARCHIVE_TIME", property="archiveTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="TRANS_FLAG", property="transFlag", jdbcType=JdbcType.VARCHAR),
            @Result(column="SPLIT_BILL_LAD_NO", property="splitBillLadNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="ENT_UUID", property="entUuid", jdbcType=JdbcType.VARCHAR),
            @Result(column="DECL_TYPE", property="declType", jdbcType=JdbcType.CHAR),
            @Result(column="ORG_CODE_PATH", property="orgCodePath", jdbcType=JdbcType.VARCHAR),
            @Result(column="DECL_STATUS", property="declStatus", jdbcType=JdbcType.CHAR),
            @Result(column="IS_FEE", property="isFee", jdbcType=JdbcType.CHAR),
            @Result(column="DECL_WORK_NO", property="declWorkNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="PURP_DEPT_CODE", property="purpDeptCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="DCL_IO_DECL_ID", property="dclIoDeclId", jdbcType=JdbcType.VARCHAR),
            @Result(column="VSA_ORG_CODE", property="vsaOrgCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="PORT_ORG_CODE", property="portOrgCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="PORT_DEPT_CODE", property="portDeptCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="INTE_FLAG", property="inteFlag", jdbcType=JdbcType.CHAR),
            @Result(column="BRI_FLAG", property="briFlag", jdbcType=JdbcType.CHAR),
            @Result(column="CHECK_OK_FLAG", property="checkOkFlag", jdbcType=JdbcType.CHAR),
            @Result(column="DIS_CHARGE_FLAG", property="disChargeFlag", jdbcType=JdbcType.CHAR),
            @Result(column="ORIG_BOX_FLAG", property="origBoxFlag", jdbcType=JdbcType.CHAR),
            @Result(column="VSA_ORG_CODE_PATH", property="vsaOrgCodePath", jdbcType=JdbcType.VARCHAR),
            @Result(column="INSP_ORG_CODE_PATH", property="inspOrgCodePath", jdbcType=JdbcType.VARCHAR),
            @Result(column="PURP_ORG_CODE_PATH", property="purpOrgCodePath", jdbcType=JdbcType.VARCHAR),
            @Result(column="PORT_ORG_CODE_PATH", property="portOrgCodePath", jdbcType=JdbcType.VARCHAR),
            @Result(column="TRANS_TYPE_TJ", property="transTypeTj", jdbcType=JdbcType.VARCHAR),
            @Result(column="OPER_TIME_TJ", property="operTimeTj", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="ENT_DATE", property="entDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<DCL_IO_DECL_TASK> listDatas(@Param("QueryTime") String QueryTime,@Param("QueryEndTime")String QueryEndTime);

    @Delete({"DELETE FROM DCL_IO_DECL_TASK WHERE DECL_NO=#{DECL_NO,jdbcType=VARCHAR}"})
    int deleteByDECL_NO(String DECL_NO);

    @Delete({"DELETE FROM DCL_IO_DECL_TASK"})
    int deleteAll();

    // OPER_TIME_TJ 及 取1W条数据都是临时字段，后期更改
    @Select({"SELECT DECL_NO,MAX(OPER_TIME_TJ) AS \"OPER_TIME_TJ\"FROM DCL_IO_DECL WHERE ROWNUM<10000 GROUP BY DECL_NO"})
    @Results({
            @Result(column ="DECL_NO",property = "DECL_NO",jdbcType =JdbcType.VARCHAR),
            @Result(column ="OPER_TIME_TJ",property = "OPER_TIME_TJ",jdbcType =JdbcType.TIMESTAMP)
    })
    List<DCL_IO_DECL_TEMP> listTempDatas();

    //根据报检单号及OPER_TIME_TJ查询数据，并插入相关数据表中
    @Insert({"insert into DCL_IO_DECL_TASK SELECT * FROM DCL_IO_DECL",
            " WHERE DECL_NO= #{DECL_NO,jdbcType=VARCHAR} AND OPER_TIME_TJ=#{OPER_TIME_TJ,jdbcType=TIMESTAMP}"})
    int batchInsert(@Param("DECL_NO") String DECL_NO,@Param("OPER_TIME_TJ") Date OPER_TIME_TJ);

}